"""filesets, transfers, limits, fair share and audit

Revision ID: 1da451ab0e43
Revises:
Create Date: 2026-08-31 21:53:09.904958

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1da451ab0e43"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_uid", sa.Integer(), nullable=False),
        sa.Column("subject_user", sa.String(length=255), nullable=False),
        sa.Column("object_type", sa.String(length=255), nullable=False),
        sa.Column("object_id", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("result", sa.String(length=255), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_events_ts", "audit_events", ["ts"], unique=False)
    op.create_table(
        "fairshare_accounts",
        sa.Column("user", sa.String(length=255), nullable=False),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("decayed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user"),
    )
    op.create_table(
        "filesets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_user", sa.String(length=255), nullable=False),
        sa.Column("owner_uid", sa.Integer(), nullable=False),
        sa.Column("owner_gid", sa.Integer(), nullable=False),
        sa.Column("storage_id", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "cached",
                "output",
                name="ck_filesetkind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "CREATING",
                "READY",
                "POPULATING",
                "FLUSHING",
                "RELEASING",
                "RELEASED",
                "FAILED",
                name="ck_filesetstate",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("allocated_bytes", sa.BigInteger(), nullable=False),
        sa.Column("used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("used_bytes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_count", sa.BigInteger(), nullable=True),
        sa.Column("over_allocation", sa.Boolean(), nullable=False),
        sa.Column("source_storage_id", sa.String(length=255), nullable=True),
        sa.Column("source_path", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("warm_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("warm_finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_flushed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_flush_target", sa.Text(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_transfer_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("allocated_bytes > 0", name="ck_filesets_allocation_positive"),
        sa.CheckConstraint("used_bytes >= 0", name="ck_filesets_used_not_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_filesets_state", "filesets", ["state"], unique=False)
    op.create_index(
        "ix_filesets_storage_owner", "filesets", ["storage_id", "owner_user"], unique=False
    )
    op.create_index(
        "uq_filesets_live_name",
        "filesets",
        ["owner_user", "storage_id", "name"],
        unique=True,
        postgresql_where=sa.text("state <> 'RELEASED'"),
    )
    op.create_table(
        "user_limits",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user", sa.String(length=255), nullable=False),
        sa.Column("storage_id", sa.String(length=255), nullable=True),
        sa.Column("allocation_limit_bytes", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_user_limits_cluster_wide",
        "user_limits",
        ["user"],
        unique=True,
        postgresql_where=sa.text("storage_id IS NULL"),
    )
    op.create_index(
        "uq_user_limits_storage", "user_limits", ["user", "storage_id"], unique=True
    )
    op.create_table(
        "transfers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "warm",
                "flush",
                "release",
                name="ck_transferkind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("user", sa.String(length=255), nullable=False),
        sa.Column("fileset_id", sa.BigInteger(), nullable=False),
        sa.Column("peer_ref", sa.Text(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "SUBMITTED",
                "ASSIGNED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                name="ck_transferstate",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("route", sa.String(length=255), nullable=False),
        sa.Column("bytes_total", sa.BigInteger(), nullable=False),
        sa.Column("bytes_done", sa.BigInteger(), nullable=False),
        sa.Column("files_total", sa.BigInteger(), nullable=True),
        sa.Column("files_done", sa.BigInteger(), nullable=True),
        sa.Column("executing_daemon_id", sa.String(length=255), nullable=True),
        sa.Column("bwlimit_bytes_per_s", sa.BigInteger(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=255), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("attempt >= 1", name="ck_transfers_attempt_positive"),
        sa.CheckConstraint(
            "bytes_done <= bytes_total", name="ck_transfers_progress_within_total"
        ),
        sa.ForeignKeyConstraint(
            ["fileset_id"],
            ["filesets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_transfers_fileset", "transfers", ["fileset_id"], unique=False)
    op.create_index(
        "ix_transfers_state_submitted", "transfers", ["state", "submitted_at"], unique=False
    )
    op.create_index("ix_transfers_user_state", "transfers", ["user", "state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transfers_user_state", table_name="transfers")
    op.drop_index("ix_transfers_state_submitted", table_name="transfers")
    op.drop_index("ix_transfers_fileset", table_name="transfers")
    op.drop_table("transfers")
    op.drop_index("uq_user_limits_storage", table_name="user_limits")
    op.drop_index(
        "uq_user_limits_cluster_wide",
        table_name="user_limits",
        postgresql_where=sa.text("storage_id IS NULL"),
    )
    op.drop_table("user_limits")
    op.drop_index(
        "uq_filesets_live_name",
        table_name="filesets",
        postgresql_where=sa.text("state <> 'RELEASED'"),
    )
    op.drop_index("ix_filesets_storage_owner", table_name="filesets")
    op.drop_index("ix_filesets_state", table_name="filesets")
    op.drop_table("filesets")
    op.drop_table("fairshare_accounts")
    op.drop_index("ix_audit_events_ts", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
